[theme]
primaryColor="#6a0dad"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0f5"
textColor="#333333"
font="sans serif"

# Disable the 'Fork' and 'GitHub' icons
[server]
enableCORS = false

[browser]
gather_usage_stats = false  # This removes the 'Made with Streamlit' branding, including the GitHub link.
